### ISSUE TITLE
Air2 Pro

### ISSUE THREAD

**Issue by traysh** [wheaney/xrealAirLinuxDriver#30]
Hey, I've got an Air 2 Pro and it's not being detected.
I've attached the `lsusb` output, please say if you need more info.

[xreal_air2_pro.txt](https://github.com/wheaney/xrealAirLinuxDriver/files/13518344/xreal_air2_pro.txt)

**Comment by traysh** [comment]
I realized I can provide more information upfront. Files attached.

[xreal_driver_log.txt](https://github.com/wheaney/xrealAirLinuxDriver/files/13518477/xreal_driver_log.txt)
[xreal_driver_config.txt](https://github.com/wheaney/xrealAirLinuxDriver/files/13518483/xreal_driver_config.txt)

`systemctl is-active xreal-air-driver` outputs `active`
`ps aux | grep xreal | grep root` outputs exactly 1 entry
the glasses are working fine as a display.

**Comment by wheaney** [comment]
I just got confirmation yesterday that my experimental build with 2 Pro support worked. I just merged that change, so it's now in the latest build of the driver and will need to work its way out to decky.

**Comment by wheaney** [comment]
In the mean time, [my Discord server](https://discord.gg/azSBTXNXMt) has instructions for installing manually if you're anxious to try it out.

**Comment by traysh** [comment]
Yes, now it is correctly detected and I can move the mouse. Thanks!

Yet, the virtual display is still not working...

**Comment by traysh** [comment]
I had the deck plugin installed, and it's working for the other options: I can disable the driver, or change it's mode to mouse and joystick. Only virtual display didn't work.

No, I've never had it working before, the only device I have is this air pro 2. I read virtual display only work with vulkan games, so I tried Portal 2 - it's vulkan, right?

**Comment by wheaney** [comment]
Air 2 Pro support has released all the way out to decky. Closing this.
